
# https://qiita.com/terukizm/items/c94f06a40be55f65d4f9
version: '3'

services:
  openproject:
    image: openproject/community:latest
    ports:
      - "30080:80"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./data:/var/db/openproject
    environment:
      SECRET_KEY_BASE: openproject_secret_key